Update dependency to latest UKCore package
NHSDigital/NHSDigital-FHIR-ImplementationGuide pull request #250
Opened 2023-02-10 12:44 UTC by omarisgreat

STU3 currentbuild v0.0.2-pre-release

Some retargeting of references to UKCore profiles required
Removal of HealthcareService specialty codes as the ValueSet is marked as extensible in UKCore

2023-02-10 12:45 UTC, omarisgreat commented
Need to review whether removal of SNOMED and eRS codes for specialty in HealthcareService examples will cause problems (including them alongside UKCorePracticeSetting codes results in warnings as the ValueSet is extensible, not preferred)

2023-02-10 14:35 UTC, KevinMayfield requested changes
eRS and Wayfinder HealthcareService are live API's and so we can't change the examples. 

Suggest we either override UKCore profile or get UKCore profile changed

2023-02-14 14:56 UTC, KevinMayfield approved these changes

2023-02-14 14:57 UTC, merged

2023-02-14 14:58 UTC, KevinMayfield commented
Running reimport in simplifier