Feature-IOPS-1513-Profiling England Provenance
NHSDigital/NHSDigital-FHIR-ImplementationGuide pull request #284
Opened 2023-06-02 19:26 UTC by KazeemHamzat

Profiling England Provenance

2023-06-05 14:18 UTC, digitalhealthmartin submitted a review, later dismissed
Identified no issues.

2023-06-06 11:20 UTC, APageNHS commented on StructureDefinition/England-Provenance.xml
> +        <targetProfile value="https://fhir.hl7.org.uk/StructureDefinition/UKCore-PractitionerRole" />
As per discussion, should not be referencing profiles

2023-06-06 11:20 UTC, APageNHS commented on StructureDefinition/England-Provenance.xml
> +        <targetProfile value="https://fhir.hl7.org.uk/StructureDefinition/UKCore-Practitioner" />
As per discussion about references

2023-06-06 11:21 UTC, APageNHS commented on StructureDefinition/England-Provenance.xml
> +        <targetProfile value="https://fhir.hl7.org.uk/StructureDefinition/UKCore-Organization" />
As per discussion about references

2023-06-06 11:21 UTC, APageNHS commented on StructureDefinition/Extension-England-ProvenanceAgent.xml
> +        <targetProfile value="https://fhir.hl7.org.uk/StructureDefinition/UKCore-PractitionerRole" />
As per discussion about references to ukcore

2023-06-08 11:00 UTC, digitalhealthmartin requested changes
Noticed few things to be addressed

2023-06-08 11:00 UTC, digitalhealthmartin commented on StructureDefinition/England-Provenance.xml
Missing `<date value="2023-06-01" />`

2023-06-08 11:00 UTC, digitalhealthmartin commented on StructureDefinition/England-Provenance.xml
> +  <description value="This profile defines the NHS England constraints and extensions on the FHIR UK Core resource [UKCore Provenance](https://simplifier.net/hl7fhirukcorer4/ukcore-provenance)." />
UKCore -> UK Core

2023-06-08 11:00 UTC, digitalhealthmartin commented on StructureDefinition/Extension-England-ProvenanceAgent.xml
> +        <targetProfile value="https://fhir.hl7.org.uk/StructureDefinition/UKCore-Practitioner" />
All targetProfiles should be removed

2023-06-12 13:09 UTC, digitalhealthmartin requested changes
Previous issues resolved. But still a few targetProfiles to remove

2023-06-12 13:09 UTC, digitalhealthmartin commented on StructureDefinition/Extension-England-ProvenanceAgent.xml
> +        <targetProfile value="https://fhir.hl7.org.uk/StructureDefinition/UKCore-Organization" />
targetProfile should be removed

2023-06-12 13:09 UTC, digitalhealthmartin commented on StructureDefinition/Extension-England-ProvenanceAgent.xml
> +        <targetProfile value="https://fhir.hl7.org.uk/StructureDefinition/UKCore-Organization" />
targetProfile should be removed

2023-06-14 14:55 UTC, digitalhealthmartin submitted a review, later dismissed
Fixed done. Approved.

2023-06-16 11:08 UTC, SheenaSharma commented
Approved.

2023-06-16 11:11 UTC, SheenaSharma approved these changes

2023-06-16 11:20 UTC, SheenaSharma requested changes
Missing Purpose.

2023-06-16 11:21 UTC, SheenaSharma commented on StructureDefinition/Extension-England-ProvenanceAgent.xml
Missing Purpose.

2023-06-21 15:38 UTC, digitalhealthmartin requested changes, later dismissed
Review CS

2023-06-21 15:38 UTC, digitalhealthmartin commented on CapabilityStatement/England-CapabilityStatement.xml
CS includes resources that are not used in this feature branch. Should just be Provenance in this CS

2023-06-22 14:19 UTC, SBajanki1 submitted a review, later dismissed

2023-06-22 14:20 UTC, SheenaSharma approved these changes, later dismissed

2023-06-22 14:30 UTC, SBajanki1 approved these changes

2023-06-22 14:30 UTC, SheenaSharma approved these changes

2023-06-22 14:34 UTC, merged