Feature/iops 1621 location
NHSDigital/NHSDigital-FHIR-ImplementationGuide pull request #293
Opened 2023-06-12 12:54 UTC by digitalhealthmartin

Note: amended system in example to use a base international system because of a continue error at validation that was not able to be resolved.

Error:
[examples › England-Location-NightingaleHospital-Example.xml › FHIR Validation: validation/src/common.js.ts#L62](https://github.com/NHSDigital/NHSEngland-FHIR-ImplementationGuide/commit/040710014af3201eb6870109ef6b5b89ceb7b345#annotation_11918376743)
expect(received).toBeFalsy()

Received: "WARNING None of the codings provided are in the value set 'V3 Value SetServiceDeliveryLocationRoleType' (http://terminology.hl7.org/ValueSet/v3-ServiceDeliveryLocationRoleType|2014-03-26), and a coding should come from this value set unless it has no suitable code (note that the validator cannot judge what is suitable) (codes = http://terminology.hl7.org/ValueSet/v3-ServiceDeliveryLocationRoleType#HOSP) [ Location - Location.type[0]] [ Location - Line 1, Col 796]

2023-06-13 12:50 UTC, KazeemHamzat requested changes

2023-06-13 12:50 UTC, KazeemHamzat commented on CodeSystem/CodeSystem-England-OrganisationRole.xml
> +<?xml version="1.0" encoding="UTF-8" standalone="no"?>
This Codesystem is a related asset to England-Organization profile but its needed here for validation. There is need to ensure they have the same content. Particularly the ID

2023-06-13 12:50 UTC, KazeemHamzat commented on StructureDefinition/Extension-England-ODSOrganizationRole.xml
> +  <purpose value="An Extension to describe what an Organization does and whether this is the primary role of the Organization." />
I will say the rule of no repetition in the NHSE CTA Dev. and guide may not allow duplicating content of description and purpose. Better to leave out purpose

2023-06-13 12:50 UTC, KazeemHamzat commented on StructureDefinition/Extension-England-ODSOrganizationRoleActivePeriod.xml
> +  <purpose value="Active period of an organization role." />
Duplicate content for description and purpose

2023-06-14 09:34 UTC, digitalhealthmartin commented
Removed unrelated files.

2023-06-16 14:43 UTC, SBajanki1 commented on valusets/ValueSet-England-LocationType.xml
> +    <compose>
Purpose is missing

2023-06-19 11:15 UTC, SheenaSharma commented on StructureDefinition/Extension-England-ODSOrganizationRole.xml
> +  <copyright value="Copyright © 2018 Health and Social Care Information Centre. NHS Digital is the trading name of the Health and Social Care Information Centre." />
Copyright text needs to be changed.

2023-07-07 12:58 UTC, digitalhealthmartin commented
**OLD PR. DO NOT MERGE. CLOSING PR.**

2023-07-07 12:58 UTC, closed without merging