Feature/iops 1621 location new
NHSDigital/NHSDigital-FHIR-ImplementationGuide pull request #307
Opened 2023-06-27 13:02 UTC by SheenaSharma

2023-06-27 18:53 UTC, KazeemHamzat approved these changes, later dismissed
Just to note that the 3 files listed below exists in both Organization and Location. We need to note them when merging.
Extension-England-ODSOrganisationRole.xml
Extension-England-ODSOrganisationRoleActivePeriod.xml
CodeSystem-England-OrganisationRole.xml

2023-06-28 09:09 UTC, SBajanki1 commented on valusets/ValueSet-England-LocationType.xml
> +	<purpose value="A ValueSet to identify the roles (type) of location." />
Date, publisher and contact details are missing

2023-06-28 09:10 UTC, SBajanki1 requested changes
Date, publisher and contact details are mising in the Valueset

2023-06-30 09:29 UTC, SBajanki1 submitted a review, later dismissed

2023-06-30 09:47 UTC, KazeemHamzat approved these changes, later dismissed

2023-06-30 10:00 UTC, SBajanki1 approved these changes

2023-06-30 10:08 UTC, KazeemHamzat approved these changes

2023-06-30 10:08 UTC, merged