Feature/iops 1622 organization new
NHSDigital/NHSDigital-FHIR-ImplementationGuide pull request #308
Opened 2023-06-27 13:10 UTC by SheenaSharma

2023-06-27 17:10 UTC, KazeemHamzat approved these changes, later dismissed

2023-06-28 08:46 UTC, SBajanki1 commented on StructureDefinition/England-Organization.xml
> +		<name value="NHS England" />
check line alignment

2023-06-28 08:51 UTC, SBajanki1 commented on valusets/ValueSet-England-OrganisationRole.xml
> +    <status value="draft" />
check line alignments

2023-06-28 08:53 UTC, SBajanki1 requested changes
Check  line alignments

2023-06-28 16:03 UTC, nhse-mf approved these changes, later dismissed

2023-06-30 09:14 UTC, SBajanki1 approved these changes, later dismissed

2023-06-30 09:33 UTC, SBajanki1 approved these changes

2023-06-30 09:33 UTC, nhse-mf approved these changes

2023-06-30 09:34 UTC, merged