Made fixes as advised by Forge
NHSDigital/NHSDigital-FHIR-ImplementationGuide pull request #333
Opened 2023-07-24 14:39 UTC by digitalhealthmartin

2023-07-28 16:40 UTC, KazeemHamzat requested changes

2023-07-28 16:40 UTC, KazeemHamzat commented on structuredefinitions/England-Location.xml
>    <differential>
Any reason why the identifier element was removed? This is not the identifier referred to in IOPS rule that negates profiling identifier.

2023-07-28 16:40 UTC, KazeemHamzat commented on structuredefinitions/England-MedicationRequest.xml
> +      <min value="0" />
Why is this cardinality changing to zero? The value for MedicationRequest.extension:NHSBSAPrescriptionType must always be supplied. The cardinality is optional on the profile but set as mandatory on IG page. May be something to clarify with @omarisgreat

2023-07-28 16:40 UTC, KazeemHamzat commented on structuredefinitions/England-MedicationRequest.xml
> -    <element id="MedicationRequest.intent">
The cardinality of MedicationRequest.intent is 1..1. Any reason to delete the element?

2023-07-28 16:40 UTC, KazeemHamzat commented on structuredefinitions/England-MedicationRequest.xml
> -    <element id="MedicationRequest.encounter">
Any reason to remove MedicationRequest.encounter from the proffile?

2023-07-28 16:40 UTC, KazeemHamzat commented on structuredefinitions/England-MedicationRequest.xml
> -    <element id="MedicationRequest.dosageInstruction.additionalInstruction">
Any reason to remove MedicationRequest.dosageInstruction.additionalInstruction & MedicationRequest.dosageInstruction.patientInstruction?

2023-07-28 16:40 UTC, KazeemHamzat commented on structuredefinitions/England-Organization.xml
> -      <max value="*" />
The cardinality for Organization.type.extension:activePeriod should be 0...1

2023-07-28 16:40 UTC, KazeemHamzat commented on structuredefinitions/England-Patient.xml
> -    <element id="Patient.address.line">
Any reason to remove Patient.address.line and Patient.multipleBirth[x] elements?

2023-07-28 16:40 UTC, KazeemHamzat commented on structuredefinitions/England-ServiceRequest.xml
> -    <element id="ServiceRequest.intent">
The cardinality of ServiceRequest.intent element is 1..1. Any reason to remove the element?

2023-07-28 16:40 UTC, KazeemHamzat commented on structuredefinitions/England-Task.xml
> -    <element id="Task.statusReason">
Any reason to remove Task.statusReason element?

2023-07-28 16:40 UTC, KazeemHamzat commented on structuredefinitions/Extension-England-ProvenanceAgent.xml
> -    <element id="Extension">
AnyrReason to remove this? element: extension

2023-07-31 09:01 UTC, digitalhealthmartin commented on structuredefinitions/England-Location.xml
>    <differential>
@KazeemHamzat This, as well as all the other changes, were done because Forge recommended these changes.

2023-07-31 12:09 UTC, KazeemHamzat approved these changes

2023-07-31 12:09 UTC, KazeemHamzat commented on structuredefinitions/England-Location.xml
>    <differential>
Further review indicated that these elements are being removed from the differentials and not the base.
This is ok.

2023-07-31 15:35 UTC, SheenaSharma approved these changes

2023-07-31 15:53 UTC, merged