Feature iops 1857 medication dispense examples
NHSDigital/NHSDigital-FHIR-ImplementationGuide pull request #336
Opened 2023-07-27 09:25 UTC by SheenaSharma

2023-07-27 09:32 UTC, KazeemHamzat submitted a review, later dismissed

2023-07-31 09:14 UTC, digitalhealthmartin requested changes

2023-07-31 09:14 UTC, digitalhealthmartin commented on examples/England-MedicationDispense-PractitionerRole-Example.xml
Some of the tags are out of alignment, for example <code></code>

2023-07-31 12:01 UTC, SheenaSharma commented
Changes are done.

2023-08-01 09:33 UTC, digitalhealthmartin approved these changes

2023-08-01 10:13 UTC, KazeemHamzat approved these changes

2023-08-01 15:51 UTC, merged