Feature iops 1859 observation examples
NHSDigital/NHSDigital-FHIR-ImplementationGuide pull request #337
Opened 2023-07-27 09:28 UTC by SheenaSharma

2023-07-28 13:32 UTC, KazeemHamzat submitted a review, later dismissed

2023-07-31 09:20 UTC, digitalhealthmartin requested changes

2023-07-31 09:20 UTC, digitalhealthmartin commented on examples/England-Patient-FredricaSmith-Example.xml
> +
Remove unnecessary blank line

2023-07-31 09:53 UTC, SheenaSharma commented
Removed the blank space from the file.

2023-07-31 12:05 UTC, KazeemHamzat submitted a review, later dismissed

2023-08-01 09:32 UTC, digitalhealthmartin submitted a review, later dismissed

2023-08-02 10:46 UTC, KazeemHamzat submitted a review, later dismissed

2023-08-02 11:09 UTC, digitalhealthmartin approved these changes

2023-08-02 11:09 UTC, KazeemHamzat approved these changes

2023-08-02 11:10 UTC, merged