Feature iops 1848 practitioner role examples
NHSDigital/NHSDigital-FHIR-ImplementationGuide pull request #339
Opened 2023-07-27 09:29 UTC by SheenaSharma

2023-07-27 10:27 UTC, KazeemHamzat approved these changes, later dismissed

2023-07-31 09:25 UTC, digitalhealthmartin requested changes

2023-07-31 09:25 UTC, digitalhealthmartin commented on examples/England-PractitionerRole-Consultant-NewExample.xml
Should remove 'NewExample' files as the original files would have been updated

2023-07-31 09:25 UTC, digitalhealthmartin commented on examples/England-PractitionerRole-GeneralSurgeryConsultant-NewExample.xml
'NewExample' issue

2023-07-31 09:48 UTC, SheenaSharma commented
Duplicate files are removed.

2023-07-31 12:04 UTC, KazeemHamzat approved these changes

2023-08-01 09:31 UTC, digitalhealthmartin approved these changes

2023-08-01 15:40 UTC, merged