Feature iops 1856 task examples
NHSDigital/NHSDigital-FHIR-ImplementationGuide pull request #341
Opened 2023-07-28 13:52 UTC by SheenaSharma

2023-07-31 09:29 UTC, digitalhealthmartin requested changes

2023-07-31 09:29 UTC, digitalhealthmartin commented on valuesets/Valueset-England-ActionCode.xml
Valueset -> ValueSet

2023-07-31 09:29 UTC, digitalhealthmartin commented on valuesets/Valueset-England-TaskCode.xml
Valueset -> ValueSet

2023-07-31 09:29 UTC, digitalhealthmartin commented on examples/England-Task-ActiveERSAdviceAndGuidance-Example.xml
Fix some alignment issues, such as <code></code>

2023-07-31 09:49 UTC, SheenaSharma commented
Changes are implemented.

2023-07-31 12:33 UTC, KazeemHamzat commented on valuesets/Valueset-England-TaskCode.xml
GitHub doesnt seem to recognise that as a change. ValueSet and Valueset are the same for it.
Changed locally but its not reflecting on GitHub.

2023-07-31 12:33 UTC, KazeemHamzat submitted a review, later dismissed

2023-08-01 09:37 UTC, digitalhealthmartin requested changes

2023-08-01 09:37 UTC, digitalhealthmartin commented on examples/England-Task-ActiveERSAdviceAndGuidance-Example.xml
There is still the alignment issues, look at code/coding

2023-08-01 10:09 UTC, SheenaSharma reviewed
Did the changes.

2023-08-01 10:15 UTC, KazeemHamzat approved these changes

2023-08-01 15:31 UTC, digitalhealthmartin approved these changes

2023-08-01 15:32 UTC, merged