Update to England-WorkFlowCodes
NHSDigital/NHSDigital-FHIR-ImplementationGuide pull request #351
Opened 2023-08-03 14:07 UTC by KazeemHamzat

-Update to England-WorkFlowCodes
-Removing Extra Quotations

2023-08-03 14:12 UTC, SheenaSharma approved these changes, later dismissed

2023-08-03 15:27 UTC, digitalhealthmartin requested changes
Change WorkflowCodes (plural) -> WorkflowCode (singular)

2023-08-03 15:27 UTC, digitalhealthmartin commented on codesystems/CodeSystem-England-WorkflowCodes.xml
Should be singular, not plural. So to become: WorkflowCode

2023-08-03 15:27 UTC, digitalhealthmartin commented on codesystems/CodeSystem-England-WorkflowCodes.xml
Drop 's' everywhere else for WorkflowCode

2023-08-03 15:27 UTC, digitalhealthmartin commented on structuredefinitions/England-Task.xml
> +      <fixedUri value="https://fhir.nhs.uk/CodeSystem/England-WorkflowCodes" />
Drop the s. Make it singular

2023-08-04 09:30 UTC, digitalhealthmartin requested changes
Just need to rename filename

2023-08-04 09:30 UTC, digitalhealthmartin commented on codesystems/CodeSystem-England-WorkflowCodes.xml
File name also needs 'drop' dropped

2023-08-04 12:06 UTC, digitalhealthmartin approved these changes

2023-08-04 12:06 UTC, SheenaSharma approved these changes

2023-08-04 12:14 UTC, merged