Feature iops 1945 spell checker corrections conflicts
NHSDigital/NHSDigital-FHIR-ImplementationGuide pull request #366
Opened 2023-08-14 11:56 UTC by KazeemHamzat

2023-08-14 15:01 UTC, digitalhealthmartin requested changes

2023-08-14 15:01 UTC, digitalhealthmartin commented on codesystems/CodeSystem-England-ERSSpecialty.xml
> +    <description value="A Codesystem use to describe ERS Specialty" />
Codesystem -> CodeSystem

2023-08-14 15:01 UTC, digitalhealthmartin commented on codesystems/CodeSystem-England-ERSSpecialty.xml
> +        <code value="CHILDREN's_ADOLESCENT_SERVICES" />
Reverse change. Changing codes not in scope.

2023-08-14 15:01 UTC, digitalhealthmartin commented on codesystems/CodeSystem-England-ERSSpecialty.xml
> +        <display value="Children's &amp; Adolescent Services" />
Reverse change. Changing codes not in scope.

2023-08-14 15:01 UTC, digitalhealthmartin commented on codesystems/CodeSystem-England-HTTPErrorCode.xml
> +        <code value="SEND_UNAUTHORISED" />
Reverse this code value changes and all code value changes.

2023-08-14 15:01 UTC, digitalhealthmartin commented on codesystems/CodeSystem-England-MessageEventEPS.xml
> +        <definition value="Can be used for an admission/discharge report or consultations"/>
consultations -> consultation

2023-08-14 15:01 UTC, digitalhealthmartin commented on codesystems/CodeSystem-England-HTTPErrorCode.xml
> +        <code value="SEND_UNAUTHORISED" />
Also reverse display name changes

2023-08-14 15:01 UTC, digitalhealthmartin commented on codesystems/CodeSystem-England-OrganisationRole.xml
> +        <display value="HOSTS DATA MANAGEMENT INTEGRATION CENTRE (DMIC)"></display>
Reverse display value changes.

2023-08-14 15:01 UTC, digitalhealthmartin commented on codesystems/CodeSystem-England-PrescriptionType.xml
> +		<display value="Primary Care Prescriber – Dietitian Supplementary prescriber"/>
Reverse changes

2023-08-14 15:01 UTC, digitalhealthmartin commented on codesystems/CodeSystem-England-PrescriptionType.xml
> +		<display value="Primary Care Prescriber – Dietitian Supplementary prescriber"/>
For this and all codes and definition values

2023-08-14 15:01 UTC, digitalhealthmartin commented on valuesets/ValueSet-England-DMPrescriptionType.xml
> +            <display value="Private prescribing - Dietitian"/>
Reverse change for this and other codes/display values

2023-08-14 15:01 UTC, digitalhealthmartin commented on valuesets/ValueSet-England-OrganisationRole.xml
> +                <display value="HOSTS DATA MANAGEMENT INTEGRATION CENTRE (DMIC)" />
Reverse change

2023-08-15 09:17 UTC, digitalhealthmartin requested changes

2023-08-15 09:17 UTC, digitalhealthmartin commented on codesystems/CodeSystem-England-HTTPErrorCode.xml
> +        <display value="405: This API doesn't allow this method." />
This needs reverting

2023-08-15 09:17 UTC, digitalhealthmartin commented on codesystems/CodeSystem-England-HTTPErrorCode.xml
> +        <display value="405: The Receiver doesn't allow this method." />
This needs reverting

2023-08-15 09:17 UTC, digitalhealthmartin commented on codesystems/CodeSystem-England-HTTPErrorCode.xml
> +        <display value="405: The Proxy doesn't allow this method." />
This needs reverting

2023-08-15 09:17 UTC, digitalhealthmartin commented on codesystems/CodeSystem-England-HTTPErrorCode.xml
> +        <definition value="The Receiver has given a 408 response to the Senders request" />
This needs reverting

2023-08-15 09:17 UTC, digitalhealthmartin commented on codesystems/CodeSystem-England-MessageEventEPS.xml
> +        <definition value="This message is used by the Dispensing System to notify the EPS System of an amendment to a previously submitted dispense-notification"/>
This needs reverting

2023-08-15 09:17 UTC, digitalhealthmartin commented on codesystems/CodeSystem-England-MessageEventEPS.xml
> +        <definition value="Can be used for an admission/discharge report or consultation"/>
This needs reverting

2023-08-15 13:50 UTC, SheenaSharma approved these changes

2023-08-15 15:49 UTC, digitalhealthmartin approved these changes

2023-08-15 15:49 UTC, merged