Feature/feature iops 1903 add naming systems
NHSDigital/NHSDigital-FHIR-ImplementationGuide pull request #377
Opened 2023-08-25 10:01 UTC by SheenaSharma

2023-08-25 13:37 UTC, digitalhealthmartin requested changes

2023-08-25 13:37 UTC, digitalhealthmartin commented on namingsystems/NamingSystem-England-ERSUBRN.xml
Add <?xml version="1.0" encoding="utf-8"?> to the top line for all files

2023-08-25 13:37 UTC, digitalhealthmartin commented on namingsystems/NamingSystem-England-ERShealthcareserice.xml
ERShealthcareservice-> ERSHealthcareService

2023-08-25 13:37 UTC, digitalhealthmartin commented on namingsystems/NamingSystem-England-ERShealthcareserice.xml
> +    <id value="NamingSystem-England-ERShealthcareserice"/>
NamingSystem-England-ERShealthcareserice-> England-ERSHealthcareService [to be discussed]

2023-08-25 13:37 UTC, digitalhealthmartin commented on namingsystems/NamingSystem-England-NhsMhsPartyKey.xml
NhsMhsPartyKey -> NHSMHSPartyKey

2023-08-25 13:37 UTC, digitalhealthmartin commented on namingsystems/NamingSystem-England-NhsMhsPartyKey.xml
And apply to id/name appropriately

2023-08-25 13:37 UTC, digitalhealthmartin commented on namingsystems/NamingSystem-England-NhsSpineASID.xml
Nhs -> NHS

2023-08-25 13:37 UTC, digitalhealthmartin commented on namingsystems/NamingSystem-England-NhsSpineASID.xml
Apply to id/name appropriately

2023-08-25 13:37 UTC, digitalhealthmartin commented on namingsystems/NamingSystem-England-PrescriptionOrderNumberns.xml
Remove 'ns' at end of filename

2023-08-25 13:37 UTC, digitalhealthmartin commented on namingsystems/NamingSystem-England-PrescriptionOrderNumberns.xml
And update id/name appropriately

2023-08-25 13:37 UTC, digitalhealthmartin commented on namingsystems/NamingSystem-England-PrescriptionOrderNumberuuidns.xml
Remove 'ns' at end and update uuid->UUID. Update id/name

2023-08-25 14:47 UTC, KazeemHamzat requested changes
Raise comments on the naming convention of elements NamingSystems.id and NamingSystems.name

2023-08-25 14:47 UTC, KazeemHamzat commented on namingsystems/NamingSystem-England-ERSUBRN.xml
> +    <id value="NamingSystem-England-ERSUBRN" />
Why is the resource type-NamingSystem, included as part of the ID?
The convention is England-[BusinessNames]. Also, the business name should be more indicative of its meaning. Thus, this ID should read England-ERSUBRNumber.
This modification will also affect the file name.

2023-08-25 14:47 UTC, KazeemHamzat commented on namingsystems/NamingSystem-England-ERSUBRN.xml
> +    <name value="NamingSystemEnglandERSUBRN" />
From above:  EnglandERSUBRNumber

2023-08-25 14:47 UTC, KazeemHamzat commented on namingsystems/NamingSystem-England-ERShealthcareserice.xml
> +    <name value="NamingSystemEnglandERShealthcareserice"/>
England-ERSHealthcareServiceID

2023-08-25 14:47 UTC, KazeemHamzat commented on namingsystems/NamingSystem-England-NhsMhsPartyKey.xml
> +    <id value="NamingSystem-England-NhsMhsPartyKey" />
England-NHSMHSPartyKey

2023-08-25 14:47 UTC, KazeemHamzat commented on namingsystems/NamingSystem-England-NhsSpineASID.xml
> +    <id value="NamingSystem-England-NhsSpineASID"/>
England-NHSSpineASID

2023-08-25 14:47 UTC, KazeemHamzat commented on namingsystems/NamingSystem-England-PrescriptionOrderItemNumber.xml
> +    <id value="NamingSystem-England-PrescriptionOrderItemNumber"/>
England-PrescriptionOrderItemNumber

2023-08-25 14:47 UTC, KazeemHamzat commented on namingsystems/NamingSystem-England-PrescriptionOrderNumberns.xml
> +    <id value="NamingSystem-England-PrescriptionOrderNumberns"/>
England-PrescriptionOrderUIDNumber

2023-08-25 14:47 UTC, KazeemHamzat commented on namingsystems/NamingSystem-England-PrescriptionOrderNumberuuidns.xml
> +    <id value="NamingSystem-England-PrescriptionOrderNumberuuidns"/>
England-PrescriptionOrderNumberUUID

2023-08-29 12:11 UTC, KazeemHamzat requested changes
Raise issues about lower case in file names

2023-08-29 12:11 UTC, KazeemHamzat commented on namingsystems/NamingSystem-England-NhsMhsPartyKey.xml
> +<?xml version="1.0" encoding="utf-8"?>
File name is yet to change to capital case.

Expect: namingsystems/NamingSystem-England-NHSMHSPartyKey.xml

2023-08-29 12:11 UTC, KazeemHamzat commented on namingsystems/NamingSystem-England-NhsSpineASID.xml
> +<?xml version="1.0" encoding="utf-8"?>
File name: namingsystems/NamingSystem-England-NHSSpineASID.xml

2023-08-29 14:30 UTC, KazeemHamzat approved these changes, later dismissed
2 Observations:
1. Only 2 of the NamingSystems have thier OID Number included at this time. In the future version, can we find out the rest and iclude them?
2. Can you go on GitHub and click Resolve Conversation button for all the issues as they have now been resolved?

2023-08-30 10:36 UTC, SheenaSharma commented
Changes are done.

2023-08-30 14:36 UTC, digitalhealthmartin requested changes

2023-08-30 14:36 UTC, digitalhealthmartin commented on namingsystems/NamingSystem-England-ERSHealthcareService.xml
> +    <description value="identifier of a healthcare service in eRS"/>
identifier -> Identifier

2023-08-30 15:31 UTC, SheenaSharma commented on namingsystems/NamingSystem-England-ERSHealthcareService.xml
> +    <description value="identifier of a healthcare service in eRS"/>
Done with the changes.

2023-08-30 15:33 UTC, digitalhealthmartin approved these changes

2023-09-04 13:55 UTC, KazeemHamzat approved these changes

2023-09-15 12:02 UTC, merged