Feature-IOPS-1829-Extension Comparisons
NHSDigital/NHSDigital-FHIR-ImplementationGuide pull request #385
Opened 2023-09-27 17:44 UTC by KazeemHamzat

This PR only has Extension Comparisons comparisons issue. Fixing inconsistencies issues in context has been stepped down for DA review.

2023-10-02 10:43 UTC, digitalhealthmartin requested changes
Considering this PR contains a lot/all of the Forge recommended changes for Profiles as it is done in the other PR, I think it's best we sort of the other one first, merge it in, then merge it into this branch, and then we should only see and review changes to Extensions as that is the scope of this PR

2023-10-02 10:43 UTC, digitalhealthmartin commented on structuredefinitions/England-Location.xml
> +      <max value="1" />
The max is * in NHSD, why just 1?

2023-10-05 13:14 UTC, digitalhealthmartin requested changes
Just a comment about the valueset

2023-10-05 13:14 UTC, digitalhealthmartin commented on valuesets/ValueSet-England-ChildProtectionPlan.xml
Why is ValueSet ChildProtectionPlan here? Surely this PR should just be about the updates to Extensions

2023-10-05 13:35 UTC, KazeemHamzat commented on valuesets/ValueSet-England-ChildProtectionPlan.xml
The merging of stu1_develop into the branch, Feature-IOPS-1829-Extension-Comparisons-and-Profile-Context-Inconsistencies to resolve conflict introduced it. It ought to come in as a new file but as I have lost my VM, while re-cloning the Repo on my laptop Git flagged it for me to commit locally to stu1_develop before I can switch branch. Then, pulling stu1_develop into the branch further downloaded it as a new file. The concern will be that only 1 file should exist for ValueSet-ChildProtectionPlan and no changes made to the existing file in stu1_develop.

2023-10-05 13:43 UTC, digitalhealthmartin approved these changes
Based on fact that I put the valueset through a diff tool and both are identical, and github is saying it's a 'modicication' and not a new file, I'm presuming it should be fine. Approving.

2023-10-05 14:27 UTC, SheenaSharma approved these changes

2023-10-05 14:37 UTC, merged