Feature-IOPS-2202-Remove-Identifier in Codesystem FGMRemovalReason & Spell Checker
NHSDigital/NHSDigital-FHIR-ImplementationGuide pull request #404
Opened 2023-10-16 12:26 UTC by KazeemHamzat

Feature-IOPS-2202-Remove-Identifier in Codesystem FGMRemovalReason & Spell Checker

2023-10-16 13:23 UTC, marcusfearnett-nhsdigital commented
Reviewed changes. Fine.

2023-10-16 13:24 UTC, marcusfearnett-nhsdigital approved these changes, later dismissed
Approve.

2023-10-16 13:40 UTC, digitalhealthmartin requested changes

2023-10-16 13:40 UTC, digitalhealthmartin commented on codesystems/CodeSystem-England-FGMRemovalReason.xml
> +  <purpose value="A codesystem used for the removal of FGM Flag." />
codesystem -> CodeSystem

2023-10-16 15:25 UTC, digitalhealthmartin approved these changes

2023-10-17 09:44 UTC, SheenaSharma approved these changes

2023-10-17 10:04 UTC, closed without merging

2023-10-17 10:04 UTC, KazeemHamzat commented
Further work has been done via another PR: https://github.com/NHSDigital/NHSEngland-FHIR-ImplementationGuide/pull/406