Feature iops 2581 add bars code system message event bars to nhse ig
NHSDigital/NHSDigital-FHIR-ImplementationGuide pull request #441
Opened 2024-06-14 11:55 UTC by SheenaSharma

2024-06-14 12:40 UTC, ryma2fhir approved these changes

2024-06-14 13:51 UTC, digitalhealthmartin requested changes

2024-06-14 13:51 UTC, digitalhealthmartin commented on CodeSystem-England-MessageEventsBars.xml
This file needs moving to codesystems folder

2024-06-14 13:51 UTC, digitalhealthmartin commented on CodeSystem-England-MessageEventsBars.xml
BARS may be better than Bars

2024-06-14 13:51 UTC, digitalhealthmartin commented on CodeSystem-England-MessageEventsBars.xml
> +    <description value="Common messaging events for Bars Service Requests." />
Suggest: A set of codes that define common messaging events for BARS Service Requests.

2024-06-14 13:51 UTC, digitalhealthmartin commented on codesystems/CodeSystem-England-MessageReasonBars.xml
> +    <description value="Message Reason codes." />
Suggest: A set of codes that define common messaging reasons for BARS Service Requests.

2024-06-14 13:51 UTC, digitalhealthmartin commented on codesystems/CodeSystem-England-MessageReasonBars.xml
Similar to other file, maybe make Bars to BARS.

2024-06-14 15:19 UTC, SheenaSharma commented on CodeSystem-England-MessageEventsBars.xml
Changes are done.

2024-06-14 15:20 UTC, SheenaSharma reviewed
Changes are done. Please review it.

2024-06-17 11:40 UTC, digitalhealthmartin approved these changes

2024-06-18 13:02 UTC, merged