GP made Optional Patient PDS
NHSDigital/NHSDigital-FHIR-ImplementationGuide pull request #451
Opened 2024-11-25 15:33 UTC by NaminderSoorma

GP made Optional Patient PDS

2024-11-26 10:10 UTC, omarisgreat requested changes
1 change requested, fine with the rest

2024-11-26 10:10 UTC, omarisgreat commented on StructureDefinition/NHSDigital-Patient-PDS.StructureDefinition.xml
> +      <min value="2" />
Could we remove the constraint on addressKey entirely? There may be up to 2 for PDS there may also be none at all.

2024-11-28 15:06 UTC, NaminderSoorma reviewed
Changes made to include EPS requirements for Patient addresskey.

2024-11-29 10:34 UTC, omarisgreat approved these changes
Looks good to me

2024-12-03 13:26 UTC, merged